### ISSUE TITLE
Allow to add GPG fingerprints

### ISSUE THREAD

**Issue by tyll** [iliana/fedora-business-cards#3]
I would like to add my GPG fingerprint to a business card. However there is not enough space in one line - it works in the text representation, but it will exceed the card in the final image. Also IMHO the fingerprint should be written in a fixed-width font. Using a GPG fingerprint should also be the default, since the short key ID is not very useful:
https://evil32.com/

**Comment by iliana** [comment]
Consider using the 64-bit key ID then.

There is a fine line between text readability on a card and presenting an entire GPG fingerprint. When this was originally developed, we erred on the side of readability and accessibility.

**Comment by tyll** [comment]
Using the full fingerprint does not make the card not readable. I saw a lot of businesscards with the full fingerprint that are perfectly fine to read. Also I do not see the purpose of putting the key ID on the business card since people need the fingerprint. And carrying extra GPG stripes with the fingerprint is not really convenient.

**Comment by iliana** [comment]
I'm not going to argue in a GitHub issue about GPG fingerprints. This was discussed and decided years ago when I first wrote this.

If you want it on the card, edit the SVG or the code.
